//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public enum ciudades {SantaCruz,Cochabamba,LaPaz}
    public partial class cliente

    {
        [Key]
        public int id_cliente { get; set; }
        [Required][Display(Name ="Nombre Completo")][StringLength(200,MinimumLength =0)]
        public string nombre { get; set; }
        [Required] [StringLength(400,MinimumLength =0)]
        public string direccion { get; set; }
        [Required]
        public int telefono { get; set; }
        public ciudades ciudad { get; set; }
    }
}
